
   Name           Domain             Range
   ----------------------------------------
   mult           <.1,3>             .2
   ----------------------------------------
   add            <.3,.2>            .4
   ----------------------------------------
   mult           <.4,3>             .5
   ----------------------------------------
   add            <.6,.5>            .7
   ----------------------------------------
   mult           <.7,3>             .8
   ----------------------------------------
   add            <.9,.8>            .10
   ----------------------------------------

 Directions -  <<in,in,in>,in> ~ out

 Wiring -  <<.9,.6,.3>,.1> ~ .10

 Inputs -  .9 .6 .3 .1
